/* tslint:disable */
/* eslint-disable */
/**
 * csignes-lsf API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AttemptCreateRequest,
  AttemptCreateResponse,
  AuthGoogleRequest,
  AuthGoogleResponse,
  Course,
  DictionaryEntry,
  Lesson,
  LessonAttempt,
  Progress,
} from '../models/index';
import {
    AttemptCreateRequestFromJSON,
    AttemptCreateRequestToJSON,
    AttemptCreateResponseFromJSON,
    AttemptCreateResponseToJSON,
    AuthGoogleRequestFromJSON,
    AuthGoogleRequestToJSON,
    AuthGoogleResponseFromJSON,
    AuthGoogleResponseToJSON,
    CourseFromJSON,
    CourseToJSON,
    DictionaryEntryFromJSON,
    DictionaryEntryToJSON,
    LessonFromJSON,
    LessonToJSON,
    LessonAttemptFromJSON,
    LessonAttemptToJSON,
    ProgressFromJSON,
    ProgressToJSON,
} from '../models/index';

export interface ApiAttemptsPostRequest {
    attemptCreateRequest: AttemptCreateRequest;
}

export interface ApiAuthGooglePostRequest {
    authGoogleRequest: AuthGoogleRequest;
}

export interface ApiCoursesCourseIdGetRequest {
    courseId: string;
}

export interface ApiLessonsLessonIdGetRequest {
    lessonId: string;
}

export interface ApiProgressMeLessonLessonIdAttemptGetRequest {
    lessonId: string;
}

export interface ApiProgressUserIdGetRequest {
    userId: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Submit my attempt for a lesson
     */
    async apiAttemptsPostRaw(requestParameters: ApiAttemptsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttemptCreateResponse>> {
        if (requestParameters['attemptCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'attemptCreateRequest',
                'Required parameter "attemptCreateRequest" was null or undefined when calling apiAttemptsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/attempts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AttemptCreateRequestToJSON(requestParameters['attemptCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttemptCreateResponseFromJSON(jsonValue));
    }

    /**
     * Submit my attempt for a lesson
     */
    async apiAttemptsPost(requestParameters: ApiAttemptsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttemptCreateResponse> {
        const response = await this.apiAttemptsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Login with Google (exchange idToken for accessToken)
     */
    async apiAuthGooglePostRaw(requestParameters: ApiAuthGooglePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthGoogleResponse>> {
        if (requestParameters['authGoogleRequest'] == null) {
            throw new runtime.RequiredError(
                'authGoogleRequest',
                'Required parameter "authGoogleRequest" was null or undefined when calling apiAuthGooglePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/google`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthGoogleRequestToJSON(requestParameters['authGoogleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthGoogleResponseFromJSON(jsonValue));
    }

    /**
     * Login with Google (exchange idToken for accessToken)
     */
    async apiAuthGooglePost(requestParameters: ApiAuthGooglePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthGoogleResponse> {
        const response = await this.apiAuthGooglePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get course by ID
     */
    async apiCoursesCourseIdGetRaw(requestParameters: ApiCoursesCourseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling apiCoursesCourseIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/courses/{courseId}`;
        urlPath = urlPath.replace(`{${"courseId"}}`, encodeURIComponent(String(requestParameters['courseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseFromJSON(jsonValue));
    }

    /**
     * Get course by ID
     */
    async apiCoursesCourseIdGet(requestParameters: ApiCoursesCourseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.apiCoursesCourseIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all courses
     */
    async apiCoursesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Course>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/courses`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CourseFromJSON));
    }

    /**
     * Get all courses
     */
    async apiCoursesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Course>> {
        const response = await this.apiCoursesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get dictionary entries
     */
    async apiDictionaryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DictionaryEntry>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dictionary`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DictionaryEntryFromJSON));
    }

    /**
     * Get dictionary entries
     */
    async apiDictionaryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DictionaryEntry>> {
        const response = await this.apiDictionaryGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get lesson by ID
     */
    async apiLessonsLessonIdGetRaw(requestParameters: ApiLessonsLessonIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Lesson>> {
        if (requestParameters['lessonId'] == null) {
            throw new runtime.RequiredError(
                'lessonId',
                'Required parameter "lessonId" was null or undefined when calling apiLessonsLessonIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/lessons/{lessonId}`;
        urlPath = urlPath.replace(`{${"lessonId"}}`, encodeURIComponent(String(requestParameters['lessonId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LessonFromJSON(jsonValue));
    }

    /**
     * Get lesson by ID
     */
    async apiLessonsLessonIdGet(requestParameters: ApiLessonsLessonIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Lesson> {
        const response = await this.apiLessonsLessonIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get my progress (authenticated)
     */
    async apiProgressMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Progress>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/progress/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProgressFromJSON(jsonValue));
    }

    /**
     * Get my progress (authenticated)
     */
    async apiProgressMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Progress> {
        const response = await this.apiProgressMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get my attempt for a lesson
     */
    async apiProgressMeLessonLessonIdAttemptGetRaw(requestParameters: ApiProgressMeLessonLessonIdAttemptGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LessonAttempt>> {
        if (requestParameters['lessonId'] == null) {
            throw new runtime.RequiredError(
                'lessonId',
                'Required parameter "lessonId" was null or undefined when calling apiProgressMeLessonLessonIdAttemptGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/progress/me/lesson/{lessonId}/attempt`;
        urlPath = urlPath.replace(`{${"lessonId"}}`, encodeURIComponent(String(requestParameters['lessonId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LessonAttemptFromJSON(jsonValue));
    }

    /**
     * Get my attempt for a lesson
     */
    async apiProgressMeLessonLessonIdAttemptGet(requestParameters: ApiProgressMeLessonLessonIdAttemptGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LessonAttempt> {
        const response = await this.apiProgressMeLessonLessonIdAttemptGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user progress (legacy - prefer /api/progress/me)
     * @deprecated
     */
    async apiProgressUserIdGetRaw(requestParameters: ApiProgressUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Progress>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiProgressUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/progress/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProgressFromJSON(jsonValue));
    }

    /**
     * Get user progress (legacy - prefer /api/progress/me)
     * @deprecated
     */
    async apiProgressUserIdGet(requestParameters: ApiProgressUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Progress> {
        const response = await this.apiProgressUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Health check
     */
    async healthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Health check
     */
    async healthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.healthGetRaw(initOverrides);
    }

}
