/* tslint:disable */
/* eslint-disable */
/**
 * csignes-lsf API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Progress } from './Progress';
import {
    ProgressFromJSON,
    ProgressFromJSONTyped,
    ProgressToJSON,
    ProgressToJSONTyped,
} from './Progress';
import type { LessonAttempt } from './LessonAttempt';
import {
    LessonAttemptFromJSON,
    LessonAttemptFromJSONTyped,
    LessonAttemptToJSON,
    LessonAttemptToJSONTyped,
} from './LessonAttempt';

/**
 * 
 * @export
 * @interface AttemptCreateResponse
 */
export interface AttemptCreateResponse {
    /**
     * 
     * @type {LessonAttempt}
     * @memberof AttemptCreateResponse
     */
    attempt: LessonAttempt;
    /**
     * 
     * @type {Progress}
     * @memberof AttemptCreateResponse
     */
    progress: Progress;
}

/**
 * Check if a given object implements the AttemptCreateResponse interface.
 */
export function instanceOfAttemptCreateResponse(value: object): value is AttemptCreateResponse {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    return true;
}

export function AttemptCreateResponseFromJSON(json: any): AttemptCreateResponse {
    return AttemptCreateResponseFromJSONTyped(json, false);
}

export function AttemptCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttemptCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'attempt': LessonAttemptFromJSON(json['attempt']),
        'progress': ProgressFromJSON(json['progress']),
    };
}

export function AttemptCreateResponseToJSON(json: any): AttemptCreateResponse {
    return AttemptCreateResponseToJSONTyped(json, false);
}

export function AttemptCreateResponseToJSONTyped(value?: AttemptCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempt': LessonAttemptToJSON(value['attempt']),
        'progress': ProgressToJSON(value['progress']),
    };
}

