/* tslint:disable */
/* eslint-disable */
/**
 * csignes-lsf API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DictionaryEntry
 */
export interface DictionaryEntry {
    /**
     * 
     * @type {string}
     * @memberof DictionaryEntry
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DictionaryEntry
     */
    word: string;
    /**
     * 
     * @type {string}
     * @memberof DictionaryEntry
     */
    videoUrl: string;
}

/**
 * Check if a given object implements the DictionaryEntry interface.
 */
export function instanceOfDictionaryEntry(value: object): value is DictionaryEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('word' in value) || value['word'] === undefined) return false;
    if (!('videoUrl' in value) || value['videoUrl'] === undefined) return false;
    return true;
}

export function DictionaryEntryFromJSON(json: any): DictionaryEntry {
    return DictionaryEntryFromJSONTyped(json, false);
}

export function DictionaryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DictionaryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'word': json['word'],
        'videoUrl': json['videoUrl'],
    };
}

export function DictionaryEntryToJSON(json: any): DictionaryEntry {
    return DictionaryEntryToJSONTyped(json, false);
}

export function DictionaryEntryToJSONTyped(value?: DictionaryEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'word': value['word'],
        'videoUrl': value['videoUrl'],
    };
}

