/* tslint:disable */
/* eslint-disable */
/**
 * csignes-lsf API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LessonStepsInner } from './LessonStepsInner';
import {
    LessonStepsInnerFromJSON,
    LessonStepsInnerFromJSONTyped,
    LessonStepsInnerToJSON,
    LessonStepsInnerToJSONTyped,
} from './LessonStepsInner';

/**
 * 
 * @export
 * @interface Lesson
 */
export interface Lesson {
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    title: string;
    /**
     * 
     * @type {Array<LessonStepsInner>}
     * @memberof Lesson
     */
    steps: Array<LessonStepsInner>;
}

/**
 * Check if a given object implements the Lesson interface.
 */
export function instanceOfLesson(value: object): value is Lesson {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function LessonFromJSON(json: any): Lesson {
    return LessonFromJSONTyped(json, false);
}

export function LessonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Lesson {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'steps': ((json['steps'] as Array<any>).map(LessonStepsInnerFromJSON)),
    };
}

export function LessonToJSON(json: any): Lesson {
    return LessonToJSONTyped(json, false);
}

export function LessonToJSONTyped(value?: Lesson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'steps': ((value['steps'] as Array<any>).map(LessonStepsInnerToJSON)),
    };
}

